# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: freeipa-fas.spec

# add or remove files that should be synced
files_to_sync:
    - freeipa-fas.spec
    - .packit.yaml
    - sources

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: freeipa-fas
# downstream (Fedora) RPM package name
downstream_package_name: freeipa-fas
upstream_tag_template: v{version}

srpm_build_deps:
    - curl

actions:
  post-upstream-clone:
    # fetch specfile, patches, documentation etc. from the downstream
    - "curl https://src.fedoraproject.org/rpms/freeipa-fas/raw/rawhide/f/freeipa-fas.spec -o freeipa-fas.spec"
    - "curl https://src.fedoraproject.org/rpms/freeipa-fas/raw/main/f/sources -o sources"
  create-archive:
    - "sh -c 'ver=$(git tag | tail -1 | sed s/v//); git archive --prefix freeipa-fas-${ver}/ HEAD -o freeipa-fas-${ver}.tar.gz'"
    - "sh -c 'echo freeipa-fas-$(git tag | tail -1 | sed s/v//).tar.gz'"

jobs:
  # upon upstream PRs, test builds
  - job: tests
    trigger: pull_request
    metadata:
      targets:
        - fedora-latest-stable
        - fedora-development

  # upon upstream releases, perform COPR builds
  - job: copr_build
    trigger: release
    metadata:
      targets:
        - fedora-latest-stable
        - fedora-development

  # upon downstream changes, create a PR upstream with sync'd files from above
  - job: sync_from_downstream
    trigger: commit

  # land upstream release in fedora dist-git - no builds
  - job: propose_downstream
    trigger: release
    metadata:
      dist_git_branches:
        - fedora-latest-stable
        - fedora-development

  # create an srpm from upstream and submit a scratch build to koji
  - job: production_build
    trigger: release
    metadata:
      targets:
        - fedora-latest-stable
        - fedora-development

  # downstream automation

  # trigger a build in koji for a new dist-git commit
  - job: koji_build
    trigger: commit
    metadata:
      dist_git_branches:
        - fedora-latest-stable
        - fedora-development

  # create a new update in bodhi for a successful koji build. directly related to `koji_build`
  - job: bodhi_update
    trigger: commit
    metadata:
      dist_git_branches:
        - fedora-latest-stable
        - fedora-development
