[tox]
envlist = lint,format,bandit,jslint
#isolated_build = true

[testenv]
passenv = HOME
deps =
    ipalib
skip_install = true

[testenv:lint]
deps = flake8
commands =
    flake8 {posargs}

[testenv:format]
deps = black
commands =
    black --check --diff {posargs:.}

[testenv:bandit]
deps = bandit
commands =
    bandit -r ipaserver/ -ll

[testenv:jslint]
deps =
skipsdist = true
set_env =
    NPM_CONFIG_PREFIX={envdir}
    NODE_PATH={envdir}/lib/node_modules
allowlist_externals =
    npm
commands =
    npm install -g globals @eslint/js @eslint/eslintrc eslint@latest
    eslint {toxinidir}/ui/js/

[flake8]
show-source = True
max-line-length = 100
ignore = E203,W503
exclude = .git,.tox,dist,*egg
